// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice_On_EFCore.Data;

#nullable disable

namespace Practice_On_EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251117000117_add- dept ,stdcourse")]
    partial class adddeptstdcourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Practice_On_EFCore.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("StdId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StdId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Title = "C#"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Title = "SQL"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Title = "Networks"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 3,
                            Title = "AI Intro"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            Title = "ML Basics"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            Title = "Algorithms"
                        });
                });

            modelBuilder.Entity("Practice_On_EFCore.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Information Systems"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AI Department"
                        });
                });

            modelBuilder.Entity("Practice_On_EFCore.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 19,
                            DepartmentId = 2,
                            Name = "Student 1"
                        },
                        new
                        {
                            Id = 2,
                            Age = 20,
                            DepartmentId = 3,
                            Name = "Student 2"
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            DepartmentId = 1,
                            Name = "Student 3"
                        },
                        new
                        {
                            Id = 4,
                            Age = 22,
                            DepartmentId = 2,
                            Name = "Student 4"
                        },
                        new
                        {
                            Id = 5,
                            Age = 23,
                            DepartmentId = 3,
                            Name = "Student 5"
                        },
                        new
                        {
                            Id = 6,
                            Age = 24,
                            DepartmentId = 1,
                            Name = "Student 6"
                        },
                        new
                        {
                            Id = 7,
                            Age = 25,
                            DepartmentId = 2,
                            Name = "Student 7"
                        },
                        new
                        {
                            Id = 8,
                            Age = 26,
                            DepartmentId = 3,
                            Name = "Student 8"
                        },
                        new
                        {
                            Id = 9,
                            Age = 27,
                            DepartmentId = 1,
                            Name = "Student 9"
                        },
                        new
                        {
                            Id = 10,
                            Age = 28,
                            DepartmentId = 2,
                            Name = "Student 10"
                        });
                });

            modelBuilder.Entity("Practice_On_EFCore.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourse");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 3
                        });
                });

            modelBuilder.Entity("Practice_On_EFCore.Models.Course", b =>
                {
                    b.HasOne("Practice_On_EFCore.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Practice_On_EFCore.Models.Student", "Student")
                        .WithMany("Courses")
                        .HasForeignKey("StdId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Practice_On_EFCore.Models.Student", b =>
                {
                    b.HasOne("Practice_On_EFCore.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Practice_On_EFCore.Models.StudentCourse", b =>
                {
                    b.HasOne("Practice_On_EFCore.Models.Course", "Course")
                        .WithMany("CoursesStudents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Practice_On_EFCore.Models.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Practice_On_EFCore.Models.Course", b =>
                {
                    b.Navigation("CoursesStudents");
                });

            modelBuilder.Entity("Practice_On_EFCore.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Practice_On_EFCore.Models.Student", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("StudentCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
